commerce_checkout.commerce_checkout_flow.*:
  type: config_entity
  label: 'Checkout flow'
  mapping:
    label:
      type: label
      label: 'Label'
    id:
      type: string
      label: 'Machine-readable name'
